### ISSUE TITLE
Do packages

### ISSUE THREAD

**Issue by GiselleSerate** [GiselleSerate/pure19prototype#4]
add to Dockerfile
current implementation doesn't do version numbers; you should definitely do version numbers

**Comment by GiselleSerate** [comment]
@jwsbrennan This is a ton of packages--can you see if we can do them all in one line as opposed to using a ton of different commands? I know that's a thing for like apt and stuff, probably also for rpm

**Comment by jwsbrennan** [comment]
So I've discovered that rpm -i <package name> does not actually work like apt-get or yum works. rpm does not search for packages, and actually can only be used to install the .rpm files you've already downloaded onto your system. I assume this means it is not the tool we want to be using? I think we should probably use yum instead, unless I've missed something in reading about rpm. I won't make the change yet, as the change should be a really minor one, because I want to make sure assuming yum is available for use on any centos system is a fair assumption.

**Comment by GiselleSerate** [comment]
yum is definitely the better utility, as I discovered [here](https://unix.stackexchange.com/questions/157448/difference-between-yum-update-vs-yum-install) and [here](https://unix.stackexchange.com/questions/36214/why-using-rpm-if-theres-yum) and [the second answer here](https://stackoverflow.com/questions/8200633/whats-the-difference-between-rpm-and-yum). My feeling after browsing is that most systems have yum (dpkg is to apt as rpm is to yum) except for Fedora 22 (according to [Wikipedia](https://en.wikipedia.org/wiki/Yum_(software)) which says it uses a rewrite of yum called DNF). It seems a reasonable assumption to say that yum or apt is on all systems, and we can move on from there?
